/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package yigitbasi.nezih.model;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Violation extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Violation\",\"namespace\":\"yigitbasi.nezih.model\",\"fields\":[{\"name\":\"businessId\",\"type\":\"int\"},{\"name\":\"date\",\"type\":\"string\"},{\"name\":\"violationTypeID\",\"type\":\"long\"},{\"name\":\"riskCategory\",\"type\":\"string\"},{\"name\":\"description\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public int businessId;
  @Deprecated public java.lang.CharSequence date;
  @Deprecated public long violationTypeID;
  @Deprecated public java.lang.CharSequence riskCategory;
  @Deprecated public java.lang.CharSequence description;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Violation() {}

  /**
   * All-args constructor.
   */
  public Violation(java.lang.Integer businessId, java.lang.CharSequence date, java.lang.Long violationTypeID, java.lang.CharSequence riskCategory, java.lang.CharSequence description) {
    this.businessId = businessId;
    this.date = date;
    this.violationTypeID = violationTypeID;
    this.riskCategory = riskCategory;
    this.description = description;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return businessId;
    case 1: return date;
    case 2: return violationTypeID;
    case 3: return riskCategory;
    case 4: return description;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: businessId = (java.lang.Integer)value$; break;
    case 1: date = (java.lang.CharSequence)value$; break;
    case 2: violationTypeID = (java.lang.Long)value$; break;
    case 3: riskCategory = (java.lang.CharSequence)value$; break;
    case 4: description = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'businessId' field.
   */
  public java.lang.Integer getBusinessId() {
    return businessId;
  }

  /**
   * Sets the value of the 'businessId' field.
   * @param value the value to set.
   */
  public void setBusinessId(java.lang.Integer value) {
    this.businessId = value;
  }

  /**
   * Gets the value of the 'date' field.
   */
  public java.lang.CharSequence getDate() {
    return date;
  }

  /**
   * Sets the value of the 'date' field.
   * @param value the value to set.
   */
  public void setDate(java.lang.CharSequence value) {
    this.date = value;
  }

  /**
   * Gets the value of the 'violationTypeID' field.
   */
  public java.lang.Long getViolationTypeID() {
    return violationTypeID;
  }

  /**
   * Sets the value of the 'violationTypeID' field.
   * @param value the value to set.
   */
  public void setViolationTypeID(java.lang.Long value) {
    this.violationTypeID = value;
  }

  /**
   * Gets the value of the 'riskCategory' field.
   */
  public java.lang.CharSequence getRiskCategory() {
    return riskCategory;
  }

  /**
   * Sets the value of the 'riskCategory' field.
   * @param value the value to set.
   */
  public void setRiskCategory(java.lang.CharSequence value) {
    this.riskCategory = value;
  }

  /**
   * Gets the value of the 'description' field.
   */
  public java.lang.CharSequence getDescription() {
    return description;
  }

  /**
   * Sets the value of the 'description' field.
   * @param value the value to set.
   */
  public void setDescription(java.lang.CharSequence value) {
    this.description = value;
  }

  /** Creates a new Violation RecordBuilder */
  public static yigitbasi.nezih.model.Violation.Builder newBuilder() {
    return new yigitbasi.nezih.model.Violation.Builder();
  }
  
  /** Creates a new Violation RecordBuilder by copying an existing Builder */
  public static yigitbasi.nezih.model.Violation.Builder newBuilder(yigitbasi.nezih.model.Violation.Builder other) {
    return new yigitbasi.nezih.model.Violation.Builder(other);
  }
  
  /** Creates a new Violation RecordBuilder by copying an existing Violation instance */
  public static yigitbasi.nezih.model.Violation.Builder newBuilder(yigitbasi.nezih.model.Violation other) {
    return new yigitbasi.nezih.model.Violation.Builder(other);
  }
  
  /**
   * RecordBuilder for Violation instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Violation>
    implements org.apache.avro.data.RecordBuilder<Violation> {

    private int businessId;
    private java.lang.CharSequence date;
    private long violationTypeID;
    private java.lang.CharSequence riskCategory;
    private java.lang.CharSequence description;

    /** Creates a new Builder */
    private Builder() {
      super(yigitbasi.nezih.model.Violation.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(yigitbasi.nezih.model.Violation.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.businessId)) {
        this.businessId = data().deepCopy(fields()[0].schema(), other.businessId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.date)) {
        this.date = data().deepCopy(fields()[1].schema(), other.date);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.violationTypeID)) {
        this.violationTypeID = data().deepCopy(fields()[2].schema(), other.violationTypeID);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.riskCategory)) {
        this.riskCategory = data().deepCopy(fields()[3].schema(), other.riskCategory);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.description)) {
        this.description = data().deepCopy(fields()[4].schema(), other.description);
        fieldSetFlags()[4] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Violation instance */
    private Builder(yigitbasi.nezih.model.Violation other) {
            super(yigitbasi.nezih.model.Violation.SCHEMA$);
      if (isValidValue(fields()[0], other.businessId)) {
        this.businessId = data().deepCopy(fields()[0].schema(), other.businessId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.date)) {
        this.date = data().deepCopy(fields()[1].schema(), other.date);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.violationTypeID)) {
        this.violationTypeID = data().deepCopy(fields()[2].schema(), other.violationTypeID);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.riskCategory)) {
        this.riskCategory = data().deepCopy(fields()[3].schema(), other.riskCategory);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.description)) {
        this.description = data().deepCopy(fields()[4].schema(), other.description);
        fieldSetFlags()[4] = true;
      }
    }

    /** Gets the value of the 'businessId' field */
    public java.lang.Integer getBusinessId() {
      return businessId;
    }
    
    /** Sets the value of the 'businessId' field */
    public yigitbasi.nezih.model.Violation.Builder setBusinessId(int value) {
      validate(fields()[0], value);
      this.businessId = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'businessId' field has been set */
    public boolean hasBusinessId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'businessId' field */
    public yigitbasi.nezih.model.Violation.Builder clearBusinessId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'date' field */
    public java.lang.CharSequence getDate() {
      return date;
    }
    
    /** Sets the value of the 'date' field */
    public yigitbasi.nezih.model.Violation.Builder setDate(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.date = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'date' field has been set */
    public boolean hasDate() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'date' field */
    public yigitbasi.nezih.model.Violation.Builder clearDate() {
      date = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'violationTypeID' field */
    public java.lang.Long getViolationTypeID() {
      return violationTypeID;
    }
    
    /** Sets the value of the 'violationTypeID' field */
    public yigitbasi.nezih.model.Violation.Builder setViolationTypeID(long value) {
      validate(fields()[2], value);
      this.violationTypeID = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'violationTypeID' field has been set */
    public boolean hasViolationTypeID() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'violationTypeID' field */
    public yigitbasi.nezih.model.Violation.Builder clearViolationTypeID() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'riskCategory' field */
    public java.lang.CharSequence getRiskCategory() {
      return riskCategory;
    }
    
    /** Sets the value of the 'riskCategory' field */
    public yigitbasi.nezih.model.Violation.Builder setRiskCategory(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.riskCategory = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'riskCategory' field has been set */
    public boolean hasRiskCategory() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'riskCategory' field */
    public yigitbasi.nezih.model.Violation.Builder clearRiskCategory() {
      riskCategory = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'description' field */
    public java.lang.CharSequence getDescription() {
      return description;
    }
    
    /** Sets the value of the 'description' field */
    public yigitbasi.nezih.model.Violation.Builder setDescription(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.description = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'description' field has been set */
    public boolean hasDescription() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'description' field */
    public yigitbasi.nezih.model.Violation.Builder clearDescription() {
      description = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    public Violation build() {
      try {
        Violation record = new Violation();
        record.businessId = fieldSetFlags()[0] ? this.businessId : (java.lang.Integer) defaultValue(fields()[0]);
        record.date = fieldSetFlags()[1] ? this.date : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.violationTypeID = fieldSetFlags()[2] ? this.violationTypeID : (java.lang.Long) defaultValue(fields()[2]);
        record.riskCategory = fieldSetFlags()[3] ? this.riskCategory : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.description = fieldSetFlags()[4] ? this.description : (java.lang.CharSequence) defaultValue(fields()[4]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
